### ISSUE TITLE
clang-11: error: unable to execute command: Executable "ld" doesn't exist!

### ISSUE THREAD

**Issue by shijl0925** [awesometic/android_kernel_samsung_msm8996#1]
when I compile lineageos ,  kernel failed. Can you help me.
branch: lineage-18.1-caf 

CHK     include/generated/compile.h
  CC      init/do_mounts.o
  CC      init/do_mounts_rd.o
  CC      init/do_mounts_initrd.o
  CC      init/do_mounts_dm.o
  CC      init/noinitramfs.o
  CC      init/initramfs.o
  CC      init/calibrate.o
  CC      init/init_task.o
  UPD     include/generated/compile.h
  CC      init/version.o
  LD      init/mounts.o
  LD      init/built-in.o
  KSYM    .tmp_kallsyms1.o
  KSYM    .tmp_kallsyms2.o
  LD      vmlinux
  SORTEX  vmlinux
  SYSMAP  System.map
  FIPS with KALSR : Generating hmac of crypto and update vmlinux... 
clang-11: error: unable to execute command: Executable "ld" doesn't exist!
clang-11: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by DDarknessOne** [comment]
I got the same error. How can i fix that?

**Comment by shijl0925** [comment]
https://github.com/awesometic/android_kernel_samsung_msm8996/commit/e2c8a5258256b375bca95f20086050087dea05b1
